### ISSUE TITLE
Options for ESM Backend

### ISSUE THREAD

**Issue by cooper-mj** [StanfordHCI/Hybrid-Physical-Digital-Spaces#1]
Hi all!

Below are a few options for the ESM backend (which do not include the out-of-the-box AWARE solution - if we could get it working, that would be ideal, but I've had significant difficulties getting it to read from the JSON, and to register the user's responses on the server... in short, there may be other better options that I'd like to explore here). Your thoughts would be more than welcome!

- [ResearchKit](https://github.com/ResearchKit/ResearchKit) with [BridgeAppSDK](https://github.com/Sage-Bionetworks/BridgeAppSDK). This would link the data from the app up to [Sage Bionetworks' Bridge Platform](http://sagebionetworks.org/bridge-platform/), a secure, HIPAA-compliant set of Sage-hosted web services and SDKs designed to support a wide variety of biomedical research studies conducted through smartphone interfaces. It appears nicely compatible with ResearchKit. This solution would mean not using the AWARE database for ESM (and perhaps, since it seems ResearchKit and HealthKit are well-integrated, we could migrate biometric sensing over to Bridge also - except this would remove some of our non-HealthKit AWARE-specific sensing capabilities we are currently using, like AWARE activity monitoring).

- Use [this tool](https://github.com/ResearchKit/ResearchKit/blob/31ea7908a24a24092ce490b7717dc8e015f77985/Testing/ORKTest/ORKTest/ORKESerialization.h) to serialize the ORKResult from a ResearchKit survey to a JSON. Options from here include converting the JSON to an SQL table (which has certainly been done - see [this StackOverFlow thread](https://stackoverflow.com/questions/40450591/converting-json-to-sql-table) or [this other StackOverFlow thread](https://stackoverflow.com/questions/8811783/convert-json-to-sqlite-in-python-how-to-map-json-keys-to-database-columns-prop)), or parsing the JSON to create a dictionary, from which we use the AWARE function `saveDataWithDictionary` function to save the results to the AWARE database.

- Manually create a survey in the app using views, text fields, and buttons. Save that data in a dictionary, then use the `saveDataWithDictionary` function to save the results of the survey to the AWARE database.

I'm sure there are more options, but these three seemed prominent to me - if there are others you would like to suggest, please do so below!

**Comment by emurnane** [comment]
Second option seems good to pursue — still integrates well with AWARE, quicker to implement, less need for from-scratch implementations!
