### ISSUE TITLE
Web study platform: create website

### ISSUE THREAD

**Issue by emurnane** [StanfordHCI/Hybrid-Physical-Digital-Spaces#14]
Create a website that can display a Qualtrics survey in the middle of the page, with a video along the border

**Comment by shridharathi** [comment]
<html>
  <head>
    <meta charset = "UTF-8">
    <title>Visual Stimulant Survey</title>
  </head>
  <body>
    <div style="display:block;position:absolute;top:0px;left:0px;z-index:998;">
      <iframe width="1280" height="660" src="https://www.youtube.com/embed/2JQynIMHUGw"
      frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope;
      picture-in-picture" allowfullscreen></iframe>
    </div>

    <div style="display:block;position:absolute;top:80px;left:160px;z-index:999;">
      <iframe src = "http://www.scsk12.org/schools/whitestation.hs/site/index.shtml" width="960" height="495"  ALLOWTRANSPARENCY="false"></iframe>
    </div>

  </body>
</html>

**Comment by cooper-mj** [comment]
Completed.
